default: &default
  adapter: postgresql
  host:     localhost
  username: postgres
  password: rails

development:
  <<: *default
  database: town_crier_development

test:
  <<: *default
  database: town_crier_test

production:
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
